Repository DestinE-Climate-DT/AQUA, pull requests merged in 2025-02, with the labels that each got.

#1691 push analysis also with rsync
  CHANGELOG.md
  cli/aqua-web/config.yaml
  cli/aqua-web/make_contents.py
  cli/aqua-web/push_analysis.sh
  docs/sphinx/source/dashboard.rst
Labels: ready to merge, dashboard

#1704 Hotfix: push_s3 compatibility with boto3>=1.36.0
  CHANGELOG.md
  cli/aqua-web/push_s3.py
Labels: fix, dashboard

#1702 [OP] Update observation dataset paths in tropical rainfall CLI configuration
  CHANGELOG.md
  diagnostics/tropical_rainfall/cli/cli_config_trop_rainfall.yml
Labels: fix, ready to merge, v0.13-operational

#1532 Update graphics test
  .gitignore
  CHANGELOG.md
  src/aqua/graphics/hovmoller.py
  tests/test_graphics.py
Labels: ready to merge, test

#1697 [OP] Fix net surface radiative flux and wind stresses in ecmean
  CHANGELOG.md
  config/diagnostics/ecmean/interface/interface_AQUA_climatedt.yaml
Labels: diagnostic, v0.13-operational

#1696 Fix net surface radiative flux and wind stresses in ecmean
  CHANGELOG.md
  config/diagnostics/ecmean/interface/interface_AQUA_climatedt.yaml
Labels: diagnostic, fix

#1708 Hotfix to catgen test
  CHANGELOG.md
  tests/test_catgen.py
Labels: ready to merge, test

#1709 [OP] Hotfix: push_s3 compatibility with boto3>=1.36.0
  CHANGELOG.md
  cli/aqua-web/push_s3.py
Labels: fix, ready to merge, dashboard

#1699 prepare readthedocs file
  .readthedocs.yaml
  CHANGELOG.md
Labels: documentation

#1716 readme and badge for documentation
  CHANGELOG.md
  README.md
Labels: documentation

#1717 Docs for operations
  .readthedocs.yaml
  README.md
Labels: documentation

#1724 Fix monthly test
  .github/workflows/aqua-complete.yml
  diagnostics/ocean3d/ocean3d/ocean_circulation/mld.py
Labels: fix, ready to merge, test

#1726 LRA zip compression for yearly files
  CHANGELOG.md
  src/aqua/lra_generator/lra_generator.py
  tests/test_lra.py
Labels: ready to merge

#1730 [OP] Enable tests for v0.13-operational
  .github/workflows/aqua.yml
  CHANGELOG.md
  src/aqua/cli/main.py
  tests/test_catgen.py
Labels: ready to merge, test, v0.13-operational

#1723 Aqua analysis configs and push_analysis options
  CHANGELOG.md
  cli/aqua-analysis/aqua-analysis.py
  cli/aqua-analysis/config.aqua-analysis.yaml
  cli/aqua-web/config.grouping.yaml
  cli/aqua-web/make_push_docs.sh
  cli/aqua-web/push_analysis.sh
  docs/sphinx/source/dashboard.rst
Labels: ready to merge, cli/scripts, dashboard

#1656 [OP] Develop more elaborate capacity to read FDB and Bridge info from file
  CHANGELOG.md
  config/catgen/production.j2
  config/catgen/reduced.j2
  docs/sphinx/source/adding_data.rst
  src/aqua/gsv/intake_gsv.py
  src/aqua/gsv/timeutil.py
  templates/catgen/config.tmpl
  tests/catgen/fdb_info_file.yaml
  tests/test_gsv.py
Labels: run tests, v0.13-operational

#1734 [OP] 0.13.2 preparation
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  CHANGELOG.md
  pyproject.toml
Labels: run tests, v0.13-operational

#1732 [v0.14] Fdb from file
  CHANGELOG.md
  config/catgen/production.j2
  config/catgen/reduced.j2
  docs/sphinx/source/adding_data.rst
  src/aqua/gsv/intake_gsv.py
  src/aqua/gsv/timeutil.py
  templates/catgen/config.tmpl
  tests/catgen/fdb_info_file.yaml
  tests/test_gsv.py
Labels: workflow, run tests

#1733 GSV intake driver instantiates GSVRetriever object only if needed
  CHANGELOG.md
  src/aqua/gsv/intake_gsv.py
Labels: framework, fix, ready to merge

#1737 Codecov extensions and badge
  .github/workflows/aqua.yml
  CHANGELOG.md
  README.md
  codecov.yml
Labels: ready to merge, run tests

#1743 Changing if statement for fixer_name in catgen
  CHANGELOG.md
  config/catgen/production.j2
  config/catgen/reduced.j2
Labels: fix, workflow, cli/scripts

#1742 [OP] Changing if statement for fixer_name in catgen
  CHANGELOG.md
  config/catgen/production.j2
  config/catgen/reduced.j2
Labels: fix, workflow, cli/scripts

#1745 Add additional command-line arguments for configuration and processing options
  CHANGELOG.md
  docs/sphinx/source/diagnostics/guidelines/default_parser.rst
  docs/sphinx/source/diagnostics/index.rst
  src/aqua_diagnostics/core/util.py
  tests/diagnostic_core/test_core_util.py
Labels: diagnostic, improvement, ready to merge

#1748 More flexible action including also Dependabot case
  .github/dependabot.yml
  .github/workflows/aqua.yml
  CHANGELOG.md
Labels: test

#1738 Further intake-gsv fixes
  CHANGELOG.md
  src/aqua/gsv/intake_gsv.py
  tests/test_gsv.py
Labels: fix, reader, ready to merge

#1752 [OP] aqua analysis bugfix
  CHANGELOG.md
  cli/aqua-analysis/aqua-analysis.py
  cli/aqua-analysis/config.aqua-analysis.yaml
Labels: run tests, v0.13-operational, ¡URGENT!

#1754 bugfix AQUA paths for diagnostics config
  CHANGELOG.md
  cli/aqua-analysis/aqua-analysis.py
  cli/aqua-analysis/config.aqua-analysis.yaml
Labels: fix, ready to merge

#1757 v0.13.3 prepare
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  CHANGELOG.md
  src/aqua/version.py
Labels: ready to merge

#1753 add metadata to each dataset
  CHANGELOG.md
  src/aqua/reader/reader.py
  tests/test_basic.py
Labels: reader

#1758 remove worthless blocks from coverage
  CHANGELOG.md
  pyproject.toml
Labels: ready to merge, test

#1749 Area selection in attribute history
  CHANGELOG.md
  src/aqua/util/sci_util.py
  tests/test_fldmean.py
Labels: framework, improvement

#1675 Test for Global Biases diagnostic
  .github/workflows/aqua-complete.yml
  CHANGELOG.md
  tests/global_biases/test_global_biases.py
Labels: diagnostic, ready to merge, test

#1767 enable EN4 regrid
  config/grids/observations.yaml
Labels: fix, ready to merge

#1762 Intake GSV can now handle fdb_info_file with only the data block
  CHANGELOG.md
  docs/sphinx/source/adding_data.rst
  src/aqua/gsv/intake_gsv.py
  tests/catgen/fdb_info_hpc-only.yaml
  tests/test_gsv.py
Labels: fix, workflow, run tests

#1761 [OP] Intake GSV can now handle fdb_info_file with only the data block
  CHANGELOG.md
  docs/sphinx/source/adding_data.rst
  src/aqua/gsv/intake_gsv.py
  tests/catgen/fdb_info_hpc-only.yaml
  tests/test_gsv.py
Labels: fix, workflow, run tests, v0.13-operational

#1769 Version to v0.13.4
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  CHANGELOG.md
  src/aqua/version.py
Labels: v0.13-operational

#1781 Add new grid defintion for hpz3 nested FESOM grid
  config/grids/tests.yaml
Labels: diagnostic, test
