Repository DestinE-Climate-DT/AQUA, pull requests merged in 2025-04, with the labels that each got.

#1855 Github authentication based on token for the catalog
  .github/workflows/aqua-complete.yml
  .github/workflows/aqua.yml
  CHANGELOG.md
  src/aqua/cli/main.py
  src/aqua/util/eccodes.py
Labels: run tests

#1828 Refactor Time Handling: Part 1
  CHANGELOG.md
  diagnostics/ocean3d/ocean3d/ocean_drifts/multi_model/time_series.py
  diagnostics/ssh/cli/ssh_cli.py
  diagnostics/ssh/ssh_class.py
  src/aqua/gsv/timeutil.py
  src/aqua/logger.py
  src/aqua/util/checksum.py
  src/aqua/util/util.py
  tests/test_lra.py
  tests/test_util.py
Labels: framework, improvement, ready to merge

#1854 Extend map function to other projections
  CHANGELOG.md
  docs/sphinx/source/figures/single_map_diff_example.png
  docs/sphinx/source/figures/single_map_example.png
  docs/sphinx/source/figures/teleconnections_ENSO_correlation_IFS-NEMO_ssp370_lra-r100-monthly_ERA5.png
  docs/sphinx/source/other_components.rst
  notebooks/graphics/single_map.ipynb
  src/aqua/graphics/__init__.py
  src/aqua/graphics/single_map.py
  src/aqua/util/graphics.py
  src/aqua_diagnostics/teleconnections/cli_teleconnections.py
  src/aqua_diagnostics/timeseries/timeseries.py
  tests/test_graphics-tools.py
  tests/test_graphics.py
Labels: improvement, ready to merge, run tests

#1865 plot_maps refactor
  CHANGELOG.md
  docs/sphinx/source/figures/maps_diff_example.png
  docs/sphinx/source/figures/maps_example.png
  docs/sphinx/source/graphics.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/other_components.rst
  notebooks/graphics/multiple_maps.ipynb
  src/aqua/graphics/multiple_maps.py
  src/aqua/graphics/single_map.py
  src/aqua/util/graphics.py
  src/aqua_diagnostics/global_biases/cli_global_biases.py
  src/aqua_diagnostics/global_biases/global_biases.py
  tests/global_biases/test_global_biases.py
  tests/test_graphics.py
Labels: framework, ready to merge

#1860 cleanup of the slurm module
  CHANGELOG.md
  docs/sphinx/source/advanced_topics.rst
  notebooks/slurm/slurm.ipynb
  pyproject.toml
  src/aqua/__init__.py
  src/aqua/slurm/__init__.py
  src/aqua/slurm/config-slurm.yml
  src/aqua/slurm/slurm.py
  tests/test_slurm.py
Labels: framework, ready to merge

#1870 fix aqua regridded
  src/aqua/lra_generator/lra_generator.py
  src/aqua/reader/reader.py
  tests/test_sci_tools.py
Labels: run tests

#1809 Local paths in config-aqua.yaml
  CHANGELOG.md
  docs/sphinx/source/advanced_topics.rst
  docs/sphinx/source/cli.rst
  docs/sphinx/source/diagnostics/guidelines/class_structure.rst
  docs/sphinx/source/getting_started.rst
  src/aqua/regridder/regridder.py
  src/aqua/util/config.py
  tests/config/config-aqua-custom.yaml
  tests/test_config.py
Labels: framework, improvement, ready to merge

#1862 AQUA internal data model for coordinate fixing
  CHANGELOG.md
  docs/sphinx/source/fixer.rst
  src/aqua/data_model/__init__.py
  src/aqua/data_model/aqua.yaml
  src/aqua/data_model/coordidentifier.py
  src/aqua/data_model/coordtranformer.py
  src/aqua/data_models/__init__.py
  src/aqua/data_models/cfcoords.py
  src/aqua/data_models/cfunits.py
  src/aqua/data_models/datamodels.py
  src/aqua/reader/fixer.py
  src/aqua/reader/reader.py
  src/aqua/util/__init__.py
  src/aqua/util/coord.py
  src/aqua_diagnostics/global_biases/global_biases.py
  tests/test_datamodel.py
Labels: framework, improvement, ready to merge

#1848 Adapt Catgen to dataportfolio v1.3.0
  .github/workflows/aqua.yml
  CHANGELOG.md
  config/catgen/catalog_entry.j2
  config/catgen/production.j2
  docs/sphinx/source/catalog_generator.rst
  src/aqua/cli/catgen.py
  templates/catgen/config.tmpl
  tests/catgen/config-test-catgen.j2
  tests/test_catgen.py
Labels: fix, ready to merge

#1832 `TimStat` refactor
  CHANGELOG.md
  docs/sphinx/source/other_components.rst
  src/aqua/lra_generator/lra_generator.py
  src/aqua/reader/reader.py
  src/aqua/timstat/__init__.py
  src/aqua/timstat/timstat.py
  tests/test_timstat.py
Labels: framework, improvement, ready to merge, run tests

#1877 Data model into AQUA config
  CHANGELOG.md
  config/data_model/aqua.yaml
  config/data_models/cf2cds.json
  config/data_models/cf2ecmwf.json
  config/data_models/ifs2cds.json
  src/aqua/cli/main.py
  src/aqua/data_model/coordidentifier.py
  src/aqua/data_model/coordtranformer.py
  tests/test_console.py
  tests/test_datamodel.py
Labels: run tests

#1876 Remove outdated documentation on make_push_docs.sh
  docs/sphinx/source/dashboard.rst
Labels: documentation

#1880 fix: update Codecov paths
  .github/workflows/aqua.yml
  codecov.yml
Labels: run tests

#1837 OutputSaver refactor
  CHANGELOG.md
  src/aqua_diagnostics/core/__init__.py
  src/aqua_diagnostics/core/output_saver.py
  tests/test_output-saver_NEW.py
Labels: improvement, run tests

#1883 improve logging of data_model
  CHANGELOG.md
  src/aqua/data_model/coordtranformer.py
Labels: run tests
