Repository DestinE-Climate-DT/AQUA, pull requests merged in 2025-10, with the labels that each got.

#2293 change berkeley in gregory
  config/diagnostics/radiation/config_radiation-timeseries.yaml
  config/diagnostics/timeseries/config_timeseries_atm.yaml
Labels: ready to merge

#2271 [Seaice] adjust timestamp dates in bias description
  src/aqua_diagnostics/seaice/plot_2d_seaice.py
Labels: diagnostic, ready to merge

#2304 Fix NAO title
  src/aqua_diagnostics/teleconnections/plot_nao.py
Labels: diagnostic, ready to merge, dashboard

#2311 Adjust timeseries and seasonal cycles title and description
  CHANGELOG.md
  src/aqua_diagnostics/timeseries/base.py
Labels: diagnostic, fix, ready to merge, dashboard

#2245 Modular area selection
  CHANGELOG.md
  config/diagnostics/teleconnections/definitions/teleconnections-destine.yaml
  diagnostics/ssh/ssh_class.py
  docs/sphinx/source/other_components.rst
  pyproject.toml
  src/aqua/accessor.py
  src/aqua/fldstat/__init__.py
  src/aqua/fldstat/area_selection.py
  src/aqua/fldstat/fldstat.py
  src/aqua/lra_generator/lra_generator.py
  src/aqua/reader/reader.py
  src/aqua/util/__init__.py
  src/aqua/util/graphics.py
  src/aqua/util/sci_util.py
  src/aqua_diagnostics/core/diagnostic.py
  src/aqua_diagnostics/seaice/seaice.py
  src/aqua_diagnostics/teleconnections/enso.py
  src/aqua_diagnostics/teleconnections/mjo.py
  src/aqua_diagnostics/teleconnections/nao.py
  tests/test_sci_tools.py
Labels: framework

#2317 Update grids for osi-saf with new generated masks
  CHANGELOG.md
  config/grids/observations.yaml
Labels: observational data

#2248 Rename LRA to DROP (Data Reduction OPerator)
  CHANGELOG.md
  cli/benchmarker/cli_benchmarker.py
  cli/drop/aqua_drop.j2
  cli/drop/auto_LRA_overnight.yaml
  cli/drop/cli_drop_parallel_slurm.py
  cli/drop/icon_lra_surface_ocean.sh
  cli/grids-downloader/grids-sync.sh
  docs/sphinx/source/aqua_console.rst
  docs/sphinx/source/drop.rst
  docs/sphinx/source/index.rst
  docs/sphinx/source/lra.rst
  docs/sphinx/source/stateoftheart_diagnostics/boxplots.rst
  docs/sphinx/source/stateoftheart_diagnostics/ecmean.rst
  docs/sphinx/source/stateoftheart_diagnostics/global_biases.rst
  docs/sphinx/source/stateoftheart_diagnostics/index.rst
  notebooks/diagnostics/ecmean/ecmean-destine.ipynb
  notebooks/drop/drop.ipynb
  notebooks/lra_generator/lra_generator.ipynb
  notebooks/reader/main.ipynb
  src/aqua/__init__.py
  src/aqua/cli/drop.py
  src/aqua/cli/main.py
  src/aqua/cli/parser.py
  src/aqua/drop/__init__.py
  src/aqua/drop/catalog_entry_builder.py
  src/aqua/drop/drop.py
  src/aqua/drop/drop_util.py
  src/aqua/drop/output_path_builder.py
  src/aqua/lra_generator/__init__.py
  templates/drop/config_drop.tmpl
  templates/drop/config_lra.tmpl
  templates/drop/config_lra_workflow.tmpl
  templates/drop/drop-submitter.tmpl
  templates/drop/drop-submitter_container.tmpl
  templates/lra/config_lra.tmpl
  tests/test_console.py
  tests/test_drop.py
  tests/test_drop_util.py
  tests/test_lra.py
Labels: improvement, ready to merge

#2320 replace osi saf with new aqua dataset
  config/diagnostics/seaice/config_seaice.yaml
  config/grids/observations.yaml
Labels: observational data, ready to merge
