Repository DestinE-Climate-DT/AQUA, pull requests merged in 2025-03, with the labels that each got.

#1782 Installation of AQUA on ECMWF HPC2020
  CHANGELOG.md
  cli/hpc2020-install/hpc2020_install.sh
  docs/sphinx/source/installation.rst
Labels: cli/scripts

#1750 Add function to load diagnostic configuration from YAML file
  CHANGELOG.md
  docs/sphinx/source/diagnostics/guidelines/core_functions.rst
  docs/sphinx/source/diagnostics/guidelines/default_parser.rst
  docs/sphinx/source/diagnostics/index.rst
  src/aqua_diagnostics/core/__init__.py
  src/aqua_diagnostics/core/util.py
  tests/diagnostic_core/test_core_util.py
Labels: diagnostic, improvement

#1783 [Op] Fix timeseries ylabel
  CHANGELOG.md
  src/aqua/graphics/timeseries.py
  src/aqua_diagnostics/timeseries/timeseries.py
Labels: diagnostic, fix, ready to merge, v0.13-operational

#1778 Add support for custom time decoding for intake driver in Reader class
  .github/workflows/aqua-complete.yml
  CHANGELOG.md
  docs/sphinx/source/adding_data.rst
  pyproject.toml
  src/aqua/reader/reader.py
  tests/test_basic.py
Labels: improvement, run tests

#1794 Update zarr dependency to allow versions >=3.0.0
  CHANGELOG.md
  environment.yml
  pyproject.toml
Labels: run tests, dependencies

#1790 Update AQUA attributes standard aspect
  CHANGELOG.md
  docs/sphinx/source/diagnostics/guidelines/class_structure.rst
  docs/sphinx/source/diagnostics/guidelines/default_parser.rst
  docs/sphinx/source/diagnostics/guidelines/output_management.rst
  docs/sphinx/source/diagnostics/index.rst
  docs/sphinx/source/other_components.rst
  src/aqua/reader/reader.py
  tests/test_basic.py
Labels: documentation, improvement

#1763 retrieve method for Diagnostic class can return data
  CHANGELOG.md
  src/aqua_diagnostics/core/diagnostic.py
Labels: diagnostic, improvement

#1711 LRA capacity to deal with regional selection
  CHANGELOG.md
  codecov.yml
  docs/sphinx/source/lra.rst
  src/aqua/cli/lra.py
  src/aqua/lra_generator/lra_generator.py
  templates/lra/config_lra.tmpl
  tests/test_lra.py
Labels: improvement, ready to merge, run tests

#1797 New fix of codecov file and env cleaning
  .github/workflows/aqua-complete.yml
  .github/workflows/aqua.yml
  CHANGELOG.md
  README.md
  cli/lumi-install/environment_lumi.yml
  codecov.yml
  environment.yml
  pyproject.toml
Labels: ready to merge, run tests

#1792 Add regrid option to relevant diagnostic cli
  CHANGELOG.md
  config/diagnostics/global_biases/config_global_biases.yaml
  diagnostics/ocean3d/cli/cli_ocean3d.py
  docs/sphinx/source/diagnostics/atm_global_mean.rst
  docs/sphinx/source/diagnostics/ocean3d.rst
  docs/sphinx/source/diagnostics/teleconnections.rst
  src/aqua_diagnostics/cli/cli_checker.py
  src/aqua_diagnostics/global_biases/cli_global_biases.py
  src/aqua_diagnostics/teleconnections/cli_teleconnections.py
Labels: ready to merge

#1801 Update test-hpz3-nested-fesom-3d configuration in tests.yaml
  config/fixes/tests.yaml
  config/grids/tests.yaml
Labels: test

#1812 [OP] correct tcc target grib code
  CHANGELOG.md
  config/fixes/convention-eccodes.yaml
Labels: fix, run tests, v0.13-operational, ¡URGENT!

#1813 [OP] GSV update to 2.9.6
  CHANGELOG.md
  pyproject.toml
Labels: v0.13-operational, ¡URGENT!

#1806 `convert_data()` as diagnostics core utility function
  CHANGELOG.md
  src/aqua_diagnostics/core/__init__.py
  src/aqua_diagnostics/core/util.py
  tests/diagnostic_core/test_core_util.py
Labels: diagnostic, improvement

#1821 [OP] Healpix 7 grids for R02B08 ICON
  CHANGELOG.md
  config/grids/ICON.yaml
Labels: fix, ready to merge, v0.13-operational

#1819 Coverage fix test
  CHANGELOG.md
  codecov.yml
  pyproject.toml
Labels: run tests

#1817 [OP] Preparation for v0.13.5
  .github/ISSUE_TEMPLATE/01-bug-report.yml
  CHANGELOG.md
  src/aqua/version.py
Labels: ready to merge, v0.13-operational

#1791 Remove usage of generator option
  CHANGELOG.md
  docs/sphinx/source/advanced_topics.rst
  docs/sphinx/source/other_components.rst
  docs/sphinx/source/reader.rst
  notebooks/reader/datasets_lumi.ipynb
  notebooks/reader/streaming.ipynb
  pyproject.toml
  src/aqua/logger.py
  src/aqua/lra_generator/lra_generator.py
  src/aqua/lra_generator/opa_generator.py
  src/aqua/reader/fixer.py
  src/aqua/reader/reader.py
  src/aqua/reader/regrid.py
  src/aqua/reader/streaming.py
  src/aqua/reader/timstat.py
  tests/test_catalog.py
  tests/test_gsv.py
  tests/test_streaming.py
Labels: framework

#1833 update base container to eccodes 2.40
  .github/workflows/aqua-complete.yml
  .github/workflows/aqua.yml
  .github/workflows/create-fdb-container.yaml
  dockerfiles/Dockerfile-development
  dockerfiles/Dockerfile.ubuntu
Labels: framework, run tests, dependencies

#1834 Check if GID exists before adding group in Dockerfile-development
  CHANGELOG.md
  dockerfiles/Dockerfile-development
Labels: framework, fix

#1768 Major refactor of `Regrid()` class
  CHANGELOG.md
  docs/sphinx/source/regrid.rst
  src/aqua/__init__.py
  src/aqua/lra_generator/lra_util.py
  src/aqua/reader/reader.py
  src/aqua/reader/reader_utils.py
  src/aqua/reader/regrid.py
  src/aqua/regridder/__init__.py
  src/aqua/regridder/griddicthandler.py
  src/aqua/regridder/regridder.py
  src/aqua/regridder/regridder_util.py
  tests/test_info.py
  tests/test_lra_util.py
  tests/test_regrid.py
Labels: framework, improvement, reader, run tests

#1729 Diagnostics Graphics Refactoring: Timeseries
  CHANGELOG.md
  config/config-aqua.tmpl
  config/styles/aqua.mplstyle
  docs/sphinx/source/other_components.rst
  docs/sphinx/source/regrid.rst
  src/aqua/cli/main.py
  src/aqua/graphics/__init__.py
  src/aqua/graphics/styles.py
  src/aqua/graphics/timeseries.py
  src/aqua/graphics/util_timeseries.py
  src/aqua_diagnostics/timeseries/gregory.py
  tests/test_configstyle.py
Labels: framework, improvement, ready to merge, run tests

#1841 Further graphical timeseries adjustments
  CHANGELOG.md
  config/styles/aqua.mplstyle
  src/aqua/graphics/timeseries.py
  src/aqua/graphics/util_timeseries.py
Labels: improvement, ready to merge

#1843 Temp catgen disable
  .github/workflows/aqua.yml
  src/aqua/version.py
Labels: improvement

#1846 WOCE-ARGO grids, fixes and datacheck
  CHANGELOG.md
  cli/checksum-checker/grids-checker.py
  cli/grids-downloader/grids-compress-upload.sh
  cli/grids-downloader/grids-downloader.sh
  config/datachecker/grids-datacheck.md5
  config/fixes/OBS-climatedt.yaml
  config/grids/observations.yaml
  src/aqua/regridder/regridder.py
Labels: improvement, observational data
